### PR TITLE
Luofan score, ask user take a picture 

### PR DESCRIPTION
**Pull request by 157123gf**

### CODE REVIEW

**Comment by phamhuutriet** [comment]
any testing? recording or screenshot to see if it works?

**Comment by 157123gf** [comment]
You can run the code on your device and see. I done testing using a phone so I dont have a screen shot

**Comment by 157123gf** [comment]
WIN_20230310_15_46_02_Pro

**Comment by 157123gf** [comment]
so there is blank picture with string 'take a picture' there and by clicking it user can take a picture

**Pull request merged**
